//! The generated test runner.
//!
//! A `test` block survives to the IR and used to stop there. The runner is what
//! makes those steps executable: it mounts the program against the emitted DOM
//! shim, then walks each test's steps, so `click` acts on a node the way a person
//! would and `expect` reads the program's own state.

use crate::codegen::expression::rewrite;
use crate::codegen::state::scope_for;
use crate::ir::{IrModule, IrTest, IrTestStep};

pub fn render(module: &IrModule) -> String {
    let mut out = String::with_capacity(2048);
    out.push_str(
        "// Generated by the Platipus compiler. Run it with `plt test` or `node tests.mjs`.\n",
    );
    out.push_str("import { readFile } from \"node:fs/promises\";\n");
    out.push_str("import { installDom } from \"./dom.mjs\";\n\n");
    out.push_str("// A bare .js file is CommonJS to Node, so the program is loaded from a\n");
    out.push_str("// data URL instead of being copied to a second name on disk.\n");
    out.push_str(
        "const source = await readFile(new URL(\"./app.js\", import.meta.url), \"utf8\");\n",
    );
    out.push_str("const url = \"data:text/javascript;base64,\" + Buffer.from(source).toString(\"base64\");\n");
    out.push_str("const program = await import(url);\n");
    out.push_str("const dom = installDom();\n");
    out.push_str("// Each test gets a fresh mount, so one test cannot leave state behind for\n");
    out.push_str("// the next. `s` and `d` are the scope the expectations were rewritten\n");
    out.push_str("// against, and the mount rebinds them.\n");
    out.push_str("let s, d;\n");
    out.push_str("function mount() {\n");
    out.push_str("  const target = new dom.Element(\"div\");\n");
    out.push_str("  const instance = program.mount(target);\n");
    out.push_str("  s = instance.s;\n");
    out.push_str("  d = instance.d;\n");
    out.push_str("  return target;\n");
    out.push_str("}\n\n");
    out.push_str("async function main(tests) {\n");
    out.push_str(RUNNER_BODY);
    out.push_str("}\n\n");
    out.push_str(RUNNER_HELPERS);
    out.push('\n');
    out.push_str("const tests = [\n");
    let scope = module.components.first().map(scope_for);
    for test in &module.tests {
        render_test(&mut out, test, scope.as_ref());
    }
    out.push_str("];\n\n");
    out.push_str("await main(tests);\n");
    out
}

fn render_test(out: &mut String, test: &IrTest, scope: Option<&crate::codegen::expression::Scope>) {
    out.push_str("  {\n");
    out.push_str(&format!("    name: {:?},\n", test.name));
    out.push_str("    steps: [\n");
    for step in &test.steps {
        match step {
            IrTestStep::Action { name, argument, .. } => {
                // An action is applied by the runner, so it is named rather than
                // inlined: a step the runner does not know is a build error. The
                // argument is already an expression in source form, so it is
                // written as it stands.
                out.push_str(&format!("      {{ kind: \"action\", name: {name:?}"));
                if let Some(argument) = argument {
                    out.push_str(&format!(", argument: {argument}"));
                }
                out.push_str(" },\n");
            }
            IrTestStep::Expect { expression, .. } => {
                let rewritten = match scope {
                    Some(scope) => rewrite(expression, scope),
                    None => expression.clone(),
                };
                // The check is emitted as a thunk rather than evaluated as text,
                // so the runner never hands program text to `eval`.
                out.push_str(&format!(
                    "      {{ kind: \"expect\", check: () => ({rewritten}), source: {expression:?} }},\n"
                ));
            }
        }
    }
    out.push_str("    ],\n");
    out.push_str("  },\n");
}

/// The body of `main`, indented by the caller. It runs after the program's tests
/// have been declared, so it can be handed them.
const RUNNER_BODY: &str = r#"let failed = 0;
for (const test of tests) {
  const target = mount();
  try {
    for (const step of test.steps) {
      if (step.kind === "action") applyAction(step, target);
      else if (!step.check()) {
        throw new Error(`expected ${step.source} to hold`);
      }
    }
    console.log(`ok   ${test.name}`);
  } catch (error) {
    failed += 1;
    console.log(`FAIL ${test.name}`);
    console.log(`     ${error.message}`);
  }
}

if (tests.length === 0) console.log("no tests declared");
console.log(`\n${tests.length - failed} passed, ${failed} failed`);
// The code is set rather than `process.exit` called, because exiting outright
// drops whatever stdout has not been flushed yet when it is a pipe.
if (failed > 0) process.exitCode = 1;
"#;

/// The helpers `main` calls. They are emitted at module scope, outside `main`,
/// so they can be read on their own.
const RUNNER_HELPERS: &str = r#"/** The node a step names, matched on the text a person would read. */
function findByText(target, text) {
  // A wrapper holds the same text as everything inside it, so the deepest match
  // is the node a person would have clicked.
  const matches = target
    .walk()
    .filter((node) => node.nodeType === 1 && node.textContent === text);
  return matches.length === 0 ? null : matches[matches.length - 1];
}

function applyAction(step, target) {
  if (step.name === "click") {
    const node = step.argument == null ? null : findByText(target, step.argument);
    if (!node) {
      throw new Error(`no node with the text ${JSON.stringify(step.argument ?? "")}`);
    }
    if (node.dispatch("click") === 0) {
      throw new Error(`the node ${JSON.stringify(step.argument)} has no click handler`);
    }
    return;
  }
  throw new Error(`unknown test action ${JSON.stringify(step.name)}`);
}
"#;

#[test]
fn the_runner_handles_every_action_the_checker_accepts() {
    use crate::semantic::events::TEST_ACTIONS;
    // The checker rejects an action outside this list, and the runner has to
    // know what each one means, so neither may fall behind the other.
    for action in TEST_ACTIONS {
        assert!(
            RUNNER_HELPERS.contains(&format!("step.name === {action:?}")),
            "the runner does not handle `{action}`",
        );
    }
}

#[test]
fn the_runner_mounts_the_program_before_it_asserts() {
    let mount = render_source("app Main { Text \"x\" }");
    let mount_at = mount
        .find("program.mount(target)")
        .expect("the runner mounts");
    let check_at = mount.find("step.check()").expect("the runner checks");
    assert!(
        mount_at < check_at,
        "the runner checks before the program is mounted"
    );
}

#[test]
fn the_runner_hands_text_to_the_program_as_written() {
    // A step argument arrives as source text, so it has to be written as it
    // stands rather than quoted a second time.
    let runner = render_source(
        r#"
app Main {
Button "+" {}
}

test clicking {
click "+"
}
"#,
    );
    assert!(runner.contains("argument: \"+\""), "{runner}");
}

#[test]
fn an_expectation_is_rewritten_against_the_program_scope() {
    let runner = render_source(
        r#"
app Main {
state count = 0
Text count
}

test counting {
expect count == 1
}
"#,
    );
    assert!(
        runner.contains("check: () => (s.count.value == 1)"),
        "{runner}"
    );
    assert!(runner.contains("source: \"count == 1\""), "{runner}");
}

#[test]
fn a_program_without_tests_still_produces_a_runner() {
    let runner = render_source("app Main { Text \"x\" }");
    assert!(runner.contains("no tests declared"), "{runner}");
}

/// Compiles a program and returns the test runner for it.
#[cfg(test)]
fn render_source(source: &str) -> String {
    let outcome = crate::parser::parse("runner.plt", source);
    assert!(
        outcome.errors.is_empty(),
        "parse errors: {:?}",
        outcome.errors
    );
    let bag = crate::semantic::SemanticChecker::new().check(&outcome.program);
    assert!(
        !bag.has_errors(),
        "semantic errors: {:?}",
        bag.errors().collect::<Vec<_>>()
    );
    let module = crate::ir::lower_program(&outcome.program).expect("lowering failed");
    render(&module)
}
