import { readFile, writeFile, rm } from "node:fs/promises";
import { existsSync } from "node:fs";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const self = path.basename(fileURLToPath(import.meta.url));
// The build directory is required; see the note in run.mjs.
const built = process.argv[2] ? path.resolve(process.argv[2]) : null;
if (!built) {
  console.error(`usage: node ${self} <build-dir>`);
  console.error(`example: plt build tests/web/fixtures/lifecycle.plt -o out && node ${self} out`);
  process.exit(2);
}
const entry = path.join(built, "app.js");

if (!existsSync(entry)) {
  console.error(`missing ${entry}; build the fixture first with \`plt build <fixture> -o ${built}\``);
  process.exit(1);
}

// The shim the compiler emits is the one under test, so the harness has no copy.
const { installDom } = await import(pathToFileURL(path.join(built, "dom.mjs")).href);

// Node treats a bare .js file as CommonJS unless a package.json says otherwise,
// so load the generated bytes through an .mjs copy instead.
const module = path.join(built, "app.mjs");
await writeFile(module, await readFile(entry, "utf8"), "utf8");

installDom();

let passed = 0;
const failures = [];

async function check(name, fn) {
  try {
    await fn();
    passed += 1;
    console.log(`ok   ${name}`);
  } catch (error) {
    failures.push({ name, error });
    console.log(`FAIL ${name}`);
    console.log(`     ${error.message}`);
  }
}

function assert(condition, message) {
  if (!condition) throw new Error(message);
}

function assertEqual(actual, expected, message) {
  if (actual !== expected) {
    throw new Error(
      `${message}: expected ${JSON.stringify(expected)}, got ${JSON.stringify(actual)}`,
    );
  }
}

const generated = await import(pathToFileURL(module).href);
const dom = await import(pathToFileURL(path.join(built, "dom.mjs")).href);
const target = new dom.Element("div");
const instance = generated.mount(target);

const log = () => instance.s.log.value;
const entries = () => log().split(";").filter(Boolean);
const count = (entry) => entries().filter((value) => value === entry).length;
const buttons = () => target.byTag("button");
const column = () => target.find((node) => node.getAttribute("class") === "plt-column");

// `update` is reported through an emitted event, so it is observed from here on
// rather than from the state log.
const traced = [];
instance.events.observed.on((entry) => traced.push(entry));
const tracedCount = (entry) => traced.filter((value) => value === entry).length;

// Holds on to nodes after they are detached, so their cleanup can be checked.
const detachedButtons = [];

await check("create runs before mount", () => {
  const order = entries();
  const before = (entry) => {
    const at = order.indexOf(entry);
    assert(at >= 0, `no ${entry} in ${log()}`);
    return at;
  };
  // A node is created before it is mounted, and the component is mounted only
  // once everything it holds is in place.
  assert(
    before("component-create") < before("component-mount"),
    `component create/mount out of order: ${log()}`,
  );
  assert(before("element-create") < before("element-mount"), log());
  assert(before("branch-create") < before("branch-mount"), log());
  assert(before("branch-mount") < before("component-mount"), log());
});

await check("element lifecycle handlers run", () => {
  for (const entry of ["element-create", "element-mount"]) {
    assert(count(entry) > 0, `no ${entry} in ${log()}`);
  }
});

await check("a node inside a template is created and mounted", () => {
  for (const entry of ["branch-create", "branch-mount"]) {
    assert(count(entry) > 0, `no ${entry} in ${log()}`);
  }
});

await check("a state write made during mount is not dropped", () => {
  // `on mount { n = 1 }` runs while the first render is still settling, so this
  // only holds if the runtime queues the write instead of discarding it.
  assertEqual(instance.s.n.value, 1, "n after mount");
  assertEqual(target.byText("1")?.textContent, "1", "the new count is not rendered");
});

await check("the follow-up render reuses the nodes it already built", () => {
  assertEqual(count("element-create"), 1, `creates in ${log()}`);
  assertEqual(buttons().length, 3, `buttons in ${log()}`);
  assertEqual(column()?.childNodes.length, 3, "column children");
});

await check("clicking re-runs update on the component and the element", () => {
  const before = traced.length;
  buttons()[0].dispatch("click");
  assert(traced.length > before, `update did not run again: ${traced.join(",")}`);
  assert(tracedCount("component-update") > 0, `no component-update in ${traced}`);
  assert(tracedCount("element-update") > 0, `no element-update in ${traced}`);
  assertEqual(instance.s.n.value, 2, "n after one click");
});

await check("removing a node runs destroy before it leaves", () => {
  const before = count("branch-destroy");
  const branch = buttons()[2];
  assert(branch != null, "the branch button is missing");
  assertEqual(branch.textContent, "branch", "the branch button text");
  detachedButtons.push(branch);
  buttons()[1].dispatch("click");
  assertEqual(instance.s.show.value, false, "the branch was not hidden");
  assert(count("branch-destroy") > before, `no branch-destroy in ${log()}`);
  assertEqual(buttons().length, 2, `buttons after hiding: ${log()}`);
  assertEqual(column()?.childNodes.length, 2, "the branch is still rendered");
});

await check("a re-render does not accumulate listeners", () => {
  const plus = buttons()[0];
  plus.dispatch("click");
  plus.dispatch("click");
  assertEqual(plus.listenerCount("click"), 1, "one click listener is expected");
  assertEqual(instance.s.n.value, 4, "n after two more clicks");
});

await check("a removed node releases its listeners", () => {
  const branch = buttons().find((node) => node.textContent === "branch");
  // The branch was hidden above, so the button that was detached has to have
  // let go of its click handler.
  assert(branch == null, "the branch button is still attached");
  const detached = detachedButtons[0];
  assertEqual(detached.listenerCount("click"), 0, "the detached button still listens");
  detached.dispatch("click");
  assertEqual(instance.s.n.value, 4, "a detached button still ran its handler");
});

await check("remounting disposes the instance it replaces", () => {
  const before = count("component-destroy");
  const second = generated.mount(target);
  assert(second !== instance, "mount returned the previous instance");
  assertEqual(instance.disposed, true, "the first instance was not disposed");
  assertEqual(second.disposed, false, "the new instance is already disposed");
  assert(
    count("component-destroy") > before,
    `component destroy did not run: ${log()}`,
  );
});

await check("a disposed instance no longer re-renders", () => {
  const before = traced.length;
  instance.s.n.value = 99;
  assertEqual(traced.length, before, "a disposed instance kept rendering");
  assertEqual(instance.s.n.value, 99, "a disposed instance swallowed the write");
});

await rm(module, { force: true });

console.log(`\n${passed} passed, ${failures.length} failed`);
// The code is set rather than `process.exit` called, because exiting outright
// drops whatever stdout has not been flushed yet when it is a pipe.
if (failures.length > 0) process.exitCode = 1;
