import { readFile, writeFile, rm, mkdir } from "node:fs/promises";
import { existsSync } from "node:fs";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const self = path.basename(fileURLToPath(import.meta.url));
// The build directory is required. `tests/web/main.rs` compiles a fixture into a
// scratch tree and passes it, and a run by hand passes whatever `plt build -o`
// wrote. There is no default, because a checked-in build directory goes stale,
// and a harness that reads one tests the checkout rather than the compiler.
const built = process.argv[2] ? path.resolve(process.argv[2]) : null;
if (!built) {
  console.error(`usage: node ${self} <build-dir>`);
  console.error(`example: plt build examples/counter.plt -o out && node ${self} out`);
  process.exit(2);
}
const entry = path.join(built, "app.js");

if (!existsSync(entry)) {
  console.error(`missing ${entry}; build the fixture first with \`plt build <fixture> -o ${built}\``);
  process.exit(1);
}

await mkdir(built, { recursive: true });
// Node treats a bare .js file as CommonJS unless a package.json says otherwise,
// so load the generated bytes through an .mjs copy instead.
const module = path.join(built, "app.mjs");
await writeFile(module, await readFile(entry, "utf8"), "utf8");

// The shim the compiler emits is the one under test, so the harness has no copy.
const { installDom } = await import(pathToFileURL(path.join(built, "dom.mjs")).href);

installDom();

let passed = 0;
const failures = [];

async function check(name, fn) {
  try {
    await fn();
    passed += 1;
    console.log(`ok   ${name}`);
  } catch (error) {
    failures.push({ name, error });
    console.log(`FAIL ${name}`);
    console.log(`     ${error.message}`);
  }
}

function assert(condition, message) {
  if (!condition) throw new Error(message);
}

function assertEqual(actual, expected, message) {
  if (actual !== expected) {
    throw new Error(`${message}: expected ${JSON.stringify(expected)}, got ${JSON.stringify(actual)}`);
  }
}

const generated = await import(pathToFileURL(module).href);
const dom = await import(pathToFileURL(path.join(built, "dom.mjs")).href);
const target = new dom.Element("div");
const instance = generated.mount(target);

const values = () =>
  target
    .walk()
    .filter((node) => node.nodeType === 1)
    .map((node) => node.textContent);

const buttons = () => target.byTag("button");
const numberNodes = () => values().filter((text) => /^\d+$/.test(text));

await check("mount renders the component tree", () => {
  assert(instance != null, "mount returned nothing");
  assertEqual(target.childNodes.length, 1, "root child count");
  assertEqual(target.childNodes[0].tagName, "DIV", "root tag");
});

await check("layout primitives reach the class attribute", () => {
  for (const name of ["plt-page", "plt-column", "plt-row"]) {
    assert(
      target.find((node) => node.getAttribute("class") === name) != null,
      `no element with class ${name}`,
    );
  }
});

await check("static text is rendered verbatim", () => {
  assertEqual(target.byText("doubled: ").textContent, "doubled: ", "static label");
});

await check("the expected buttons are generated", () => {
  const labels = buttons().map((button) => button.textContent);
  assertEqual(JSON.stringify(labels), JSON.stringify(["-1", "+1", "reset"]), "button labels");
});

await check("initial state and derived value are both zero", () => {
  assertEqual(JSON.stringify(numberNodes()), JSON.stringify(["0", "0"]), "initial numbers");
});

await check("clicking +1 updates the count and the derived value", () => {
  buttons()[1].dispatch("click");
  assertEqual(JSON.stringify(numberNodes()), JSON.stringify(["1", "2"]), "after +1");
});

await check("derived values keep tracking across repeated updates", () => {
  const plus = buttons()[1];
  plus.dispatch("click");
  plus.dispatch("click");
  assertEqual(JSON.stringify(numberNodes()), JSON.stringify(["3", "6"]), "after two more +1");
});

await check("clicking -1 decrements the count", () => {
  buttons()[0].dispatch("click");
  assertEqual(JSON.stringify(numberNodes()), JSON.stringify(["2", "4"]), "after -1");
});

await check("reset returns everything to zero", () => {
  buttons()[2].dispatch("click");
  assertEqual(JSON.stringify(numberNodes()), JSON.stringify(["0", "0"]), "after reset");
});

await check("the mount target keeps a handle on the instance", () => {
  assert(target.__plt != null, "target.__plt was not set");
  assertEqual(target.__plt.root, target.childNodes[0], "instance root");
});

await rm(module, { force: true });

console.log(`\n${passed} passed, ${failures.length} failed`);
// The code is set rather than `process.exit` called, because exiting outright
// drops whatever stdout has not been flushed yet when it is a pipe.
if (failures.length > 0) process.exitCode = 1;
