


use std::path::Path;
use std::process::Command;

use crate::ast::Program;
use crate::diagnostics::{DiagnosticBag, Error, ErrorKind, Span};

pub use platipus_language::rust_extract::{RustExport, RustExtraction, extract_rust};
pub use platipus_language::rust_types::check_signature;

/// How much of the Rust toolchain to run.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum RustMode {
    /// Type-check only (`cargo check`); used by `plt check`.
    Check,
    /// Full build (`cargo build`); used by `plt build`.
    Build,
}

/// Compiles the program's Rust blocks. Returns `Ok(None)` when the program
/// contains no `#[rust]` blocks.
pub fn compile_rust(
    program: &Program,
    workdir: &Path,
    mode: RustMode,
) -> Result<Option<RustCompilation>, DiagnosticBag> {
    compile_rust_with_deps(program, workdir, mode, &[])
}

/// Compiles the program's Rust blocks, forwarding any declared
/// `[rust.dependencies]` from the P2LT manifest into the generated Cargo
/// crate. P2LT stays the owner of Platipus packages; Cargo keeps resolving
/// Rust crates.
pub fn compile_rust_with_deps(
    program: &Program,
    workdir: &Path,
    mode: RustMode,
    rust_dependencies: &[(String, String)],
) -> Result<Option<RustCompilation>, DiagnosticBag> {
    let extraction = match extract_rust(program)? {
        Some(extraction) => extraction,
        None if !rust_dependencies.is_empty() => RustExtraction {
            source: String::new(),
            source_start: 0,
            block_offsets: Vec::new(),
            exports: Vec::new(),
        },
        None => return Ok(None),
    };

    let crate_root = workdir.join("target").join("rust");
    let src_dir = crate_root.join("src");
    if let Err(error) = std::fs::create_dir_all(&src_dir) {
        let mut bag = DiagnosticBag::new();
        bag.error(
            Error::new(
                ErrorKind::Io,
                "rust-io",
                format!("cannot create {}: {error}", src_dir.display()),
            )
            .with_span(Span::empty()),
        );
        return Err(bag);
    }

    let mut lib_source = String::from("// generated by the Platipus compiler\n");
    // Remember, in lib.rs line numbers (1-based), where each .plt block's
    // source begins, so cargo errors can be mapped back.
    let mut block_line_map: Vec<(usize, usize, u32)> = Vec::new();
    lib_source.push_str(&extraction.source);
    block_line_map.push((2, extraction.source.lines().count(), extraction.source_start));

    // Extern wrappers come after the extraction source; errors there map to
    // the export's own span.
    let mut provenance: Vec<(usize, usize)> = Vec::new();
    let any_string = extraction.exports.iter().any(|export| {
        export.params.iter().any(|(_, ty)| ty == "String")
            || export.return_type.as_deref() == Some("String")
    });
    if any_string {
        lib_source.push_str(
            "\n#[no_mangle]\npub extern \"C\" fn __pltAlloc(len: i32) -> i32 {\n    let mut v: Vec<u8> = Vec::with_capacity(len.max(0) as usize);\n    v.resize(len.max(0) as usize, 0);\n    let ptr = v.as_mut_ptr();\n    std::mem::forget(v);\n    ptr as i32\n}\n",
        );
    }

    for export in &extraction.exports {
        let uses_string = export
            .params
            .iter()
            .any(|(_, ty)| ty == "String")
            || export.return_type.as_deref() == Some("String");
        let start_line = lib_source.lines().count() + 1;
        if uses_string {
            let mut params_decl: Vec<String> = Vec::new();
            for (name, ty) in &export.params {
                if ty == "String" {
                    params_decl.push(format!("{name}_ptr: i32"));
                    params_decl.push(format!("{name}_len: i32"));
                } else {
                    params_decl.push(format!("{name}: {ty}"));
                }
            }
            let mut body = String::new();
            let mut call_args: Vec<String> = Vec::new();
            for (name, ty) in &export.params {
                if ty == "String" {
                    body.push_str(&format!(
                        "    let {name} = String::from_utf8(unsafe {{ Vec::from_raw_parts({name}_ptr as *mut u8, {name}_len as usize, {name}_len as usize) }}).unwrap();\n"
                    ));
                    call_args.push(name.clone());
                } else {
                    call_args.push(name.clone());
                }
            }
            let is_string_ret = export.return_type.as_deref() == Some("String");
            let ret_decl = if is_string_ret {
                " -> u64".to_string()
            } else {
                match &export.return_type {
                    Some(ty) => format!(" -> {ty}"),
                    None => String::new(),
                }
            };
            if is_string_ret {
                body.push_str(&format!(
                    "    let out = {}({});\n    let mut v = out.into_bytes();\n    let len = v.len();\n    let ptr = v.as_mut_ptr();\n    std::mem::forget(v);\n    ((ptr as u64) << 32) | (len as u64)\n",
                    export.impl_name,
                    call_args.join(", ")
                ));
            } else {
                body.push_str(&format!(
                    "    {}({})\n",
                    export.impl_name,
                    call_args.join(", ")
                ));
            }
            lib_source.push_str(&format!(
                "\n#[no_mangle]\npub extern \"C\" fn {}({}){} {{\n{}}}\n",
                export.name,
                params_decl.join(", "),
                ret_decl,
                body
            ));
        } else {
            let params = export
                .params
                .iter()
                .map(|(name, ty)| format!("{name}: {ty}"))
                .collect::<Vec<_>>()
                .join(", ");
            let ret = match &export.return_type {
                Some(ty) => format!(" -> {ty}"),
                None => String::new(),
            };
            let args = export
                .params
                .iter()
                .map(|(name, _)| name.clone())
                .collect::<Vec<_>>()
                .join(", ");
            lib_source.push_str(&format!(
                "\n#[no_mangle]\npub extern \"C\" fn {}({}){} {{ {}({}) }}\n",
                export.name, params, ret, export.impl_name, args
            ));
        }
        provenance.push((start_line, export.plt_offset));
    }

    let mut cargo_toml = String::from(
        "[package]\nname = \"platipus_rust\"\nversion = \"0.0.0\"\nedition = \"2021\"\n\n[lib]\nname = \"platipus_rust\"\ncrate-type = [\"cdylib\", \"rlib\"]\n\n[workspace]\n",
    );
    if !rust_dependencies.is_empty() {
        cargo_toml.push_str("\n[dependencies]\n");
        for (name, version) in rust_dependencies {
            cargo_toml.push_str(&format!("{name} = \"{version}\"\n"));
        }
    }
    write_file(crate_root.join("Cargo.toml"), &cargo_toml)?;
    write_file(src_dir.join("lib.rs"), &lib_source)?;

    let toolchain_ok = Command::new("cargo")
        .arg("--version")
        .output()
        .map(|output| output.status.success())
        .unwrap_or(false);
    if !toolchain_ok {
        let mut bag = DiagnosticBag::new();
        bag.error(
            Error::new(
                ErrorKind::Cli,
                "rust-not-found",
                "Rust toolchain was not found",
            )
            .with_help(
                "Install Rust from the official Rust toolchain and make sure `cargo` and `rustc` are available in PATH.",
            ),
        );
        return Err(bag);
    }

    let mut command = Command::new("cargo");
    command.current_dir(&crate_root);
    command.arg(match mode {
        RustMode::Check => "check",
        RustMode::Build => "build",
    });
    command.arg("--release");
    let use_wasm = wasm_target_installed();
    if use_wasm && mode == RustMode::Build {
        command.arg("--target").arg("wasm32-unknown-unknown");
    }
    let output = command.output().map_err(|e| {
        let mut bag = DiagnosticBag::new();
        bag.error(Error::new(ErrorKind::Io, "rust-io", e.to_string()));
        bag
    })?;
    if output.status.success() {
        let exports = extraction.exports.clone();
        let mut wasm_path = None;
        if use_wasm && mode == RustMode::Build {
            let candidate = crate_root
                .join("target")
                .join("wasm32-unknown-unknown")
                .join("release")
                .join("platipus_rust.wasm");
            if candidate.exists() {
                wasm_path = Some(candidate);
            }
        }
        Ok(Some(RustCompilation {
            source: lib_source,
            exports,
            block_line_map,
            provenance,
            wasm_path,
        }))
    } else {
        let stderr = String::from_utf8_lossy(&output.stderr);
        let mut bag = DiagnosticBag::new();
        bag.error(map_cargo_error(
            &stderr,
            &extraction,
            &block_line_map,
            &provenance,
        ));
        Err(bag)
    }
}

fn write_file(path: impl AsRef<Path>, contents: &str) -> Result<(), DiagnosticBag> {
    std::fs::write(path, contents).map_err(|e| {
        let mut bag = DiagnosticBag::new();
        bag.error(Error::new(ErrorKind::Io, "rust-io", e.to_string()));
        bag
    })
}

fn wasm_target_installed() -> bool {
    Command::new("rustup")
        .args(["target", "list", "--installed"])
        .output()
        .map(|output| String::from_utf8_lossy(&output.stdout).contains("wasm32-unknown-unknown"))
        .unwrap_or(false)
}

/// What the caller needs to bridge Rust into the generated web app.
#[derive(Debug, Clone)]
pub struct RustCompilation {
    pub source: String,
    pub exports: Vec<RustExport>,
    /// (lib.rs line, count, plt offset) per block, for error mapping.
    pub block_line_map: Vec<(usize, usize, u32)>,
    /// (lib.rs line of each wrapper, plt offset of the export).
    pub provenance: Vec<(usize, usize)>,
    /// Path to the built wasm artifact, when a wasm target was built.
    pub wasm_path: Option<std::path::PathBuf>,
}

/// Base64 encodes bytes (standard alphabet, with padding) without needing an
/// external crate.
pub fn base64_encode(data: &[u8]) -> String {
    const TABLE: &[u8; 64] = b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
    let mut out = String::with_capacity(data.len().div_ceil(3) * 4);
    for chunk in data.chunks(3) {
        let b0 = chunk[0] as u32;
        let b1 = chunk.get(1).map(|b| *b as u32).unwrap_or(0);
        let b2 = chunk.get(2).map(|b| *b as u32).unwrap_or(0);
        let n = (b0 << 16) | (b1 << 8) | b2;
        out.push(TABLE[((n >> 18) & 63) as usize] as char);
        out.push(TABLE[((n >> 12) & 63) as usize] as char);
        if chunk.len() > 1 {
            out.push(TABLE[((n >> 6) & 63) as usize] as char);
        } else {
            out.push('=');
        }
        if chunk.len() > 2 {
            out.push(TABLE[(n & 63) as usize] as char);
        } else {
            out.push('=');
        }
    }
    out
}

/// Maps a `lines `--> path:line:col` cargo error into a .plt diagnostic.
fn map_cargo_error(
    stderr: &str,
    extraction: &RustExtraction,
    block_line_map: &[(usize, usize, u32)],
    provenance: &[(usize, usize)],
) -> Error {
    let mut message = first_error_line(stderr);
    let mut span = Span::empty();
    if let Some(lib_line) = find_location_line(stderr) {
        for &(start_line, count, plt_start) in block_line_map {
            if lib_line >= start_line && lib_line < start_line + count {
                // Count lines inside extraction source.
                let mut offset = extraction.source_start as usize;
                for (i, slice) in extraction.source.split_inclusive('\n').enumerate() {
                    if i + 2 == lib_line {
                        return finish(stderr, message, Span::new(offset as u32, offset as u32));
                    }
                    offset += slice.len();
                }
                span = Span::new(plt_start, plt_start);
                break;
            }
        }
        for &(start_line, plt_offset) in provenance {
            if lib_line >= start_line && lib_line < start_line + 4 {
                span = Span::new(plt_offset as u32, plt_offset as u32);
                break;
            }
        }
    }
    finish(stderr, std::mem::take(&mut message), span)
}

fn finish(stderr: &str, message: String, span: Span) -> Error {
    let mut error =
        Error::new(ErrorKind::Semantic, "rust-compile", message.trim().to_string())
            .with_span(span);
    if stderr.lines().count() > 1 {
        let snippet = stderr.lines().take(20).collect::<Vec<_>>().join("\n");
        error = error.with_note(crate::diagnostics::Note::new(snippet));
    }
    error
}

fn first_error_line(stderr: &str) -> String {
    for line in stderr.lines() {
        if line.starts_with("error") {
            return line.to_string();
        }
    }
    stderr.lines().next().unwrap_or("Rust compilation failed").to_string()
}

fn find_location_line(stderr: &str) -> Option<usize> {
    for line in stderr.lines() {
        if let Some(rest) = line.trim_start().strip_prefix("--> ") {
            // "--> src/lib.rs:LINE:COL"
            let parts: Vec<&str> = rest.split(':').collect();
            if parts.len() >= 3 {
                if let Ok(line) = parts[parts.len() - 2].parse::<usize>() {
                    return Some(line);
                }
            }
        }
    }
    None
}
