[package]
name = "platipus-runtime"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Runtime for the Platipus UI Application Programming Language"

[lib]
name = "platipus_runtime"
path = "src/lib.rs"
crate-type = ["rlib"]

[dependencies]
