// Generated by the Platipus compiler. Run it with `plt test` or `node tests.mjs`.
import { readFile } from "node:fs/promises";
import { installDom } from "./dom.mjs";

// A bare .js file is CommonJS to Node, so the program is loaded from a
// data URL instead of being copied to a second name on disk.
const source = await readFile(new URL("./app.js", import.meta.url), "utf8");
const url = "data:text/javascript;base64," + Buffer.from(source).toString("base64");
const program = await import(url);
const dom = installDom();
// Each test gets a fresh mount, so one test cannot leave state behind for
// the next. `s` and `d` are the scope the expectations were rewritten
// against, and the mount rebinds them.
let s, d;
function mount() {
  const target = new dom.Element("div");
  const instance = program.mount(target);
  s = instance.s;
  d = instance.d;
  return target;
}

async function main(tests) {
let failed = 0;
for (const test of tests) {
  const target = mount();
  try {
    for (const step of test.steps) {
      if (step.kind === "action") applyAction(step, target);
      else if (!step.check()) {
        throw new Error(`expected ${step.source} to hold`);
      }
    }
    console.log(`ok   ${test.name}`);
  } catch (error) {
    failed += 1;
    console.log(`FAIL ${test.name}`);
    console.log(`     ${error.message}`);
  }
}

if (tests.length === 0) console.log("no tests declared");
console.log(`\n${tests.length - failed} passed, ${failed} failed`);
// The code is set rather than `process.exit` called, because exiting outright
// drops whatever stdout has not been flushed yet when it is a pipe.
if (failed > 0) process.exitCode = 1;
}

/** The node a step names, matched on the text a person would read. */
function findByText(target, text) {
  // A wrapper holds the same text as everything inside it, so the deepest match
  // is the node a person would have clicked.
  const matches = target
    .walk()
    .filter((node) => node.nodeType === 1 && node.textContent === text);
  return matches.length === 0 ? null : matches[matches.length - 1];
}

function applyAction(step, target) {
  if (step.name === "click") {
    const node = step.argument == null ? null : findByText(target, step.argument);
    if (!node) {
      throw new Error(`no node with the text ${JSON.stringify(step.argument ?? "")}`);
    }
    if (node.dispatch("click") === 0) {
      throw new Error(`the node ${JSON.stringify(step.argument)} has no click handler`);
    }
    return;
  }
  throw new Error(`unknown test action ${JSON.stringify(step.name)}`);
}

const tests = [
];

await main(tests);
