//! The DOM shim the generated test runner stands on.
//!
//! It is emitted next to the program rather than kept in the repository so that
//! a built artifact carries everything it needs to be exercised, and so the
//! shim a project is tested against is the same one the compiler ships.

/// A minimal DOM, enough for the generated runtime to mount and patch a tree.
///
/// Only what the runtime touches is modelled: node identity, the tree, text,
/// attributes, and event listeners. A browser offers more, but a test runner
/// only has to be right about what the program under test reaches for.
pub const SOURCE: &str = r#"// Generated by the Platipus compiler. A minimal DOM for the test runner.
class ClassList {
  constructor(node) {
    this.node = node;
  }

  add(name) {
    const current = this.node.attributes["class"];
    const parts = current ? current.split(/\s+/).filter(Boolean) : [];
    if (!parts.includes(name)) parts.push(name);
    this.node.attributes["class"] = parts.join(" ");
  }
}

class Node_ {
  constructor(nodeType) {
    this.nodeType = nodeType;
    this.childNodes = [];
    this.parentNode = null;
  }

  append(...children) {
    for (const child of children) {
      child.remove();
      child.parentNode = this;
      this.childNodes.push(child);
    }
  }

  insertBefore(child, reference) {
    // A real insert moves the node, so it leaves its old position first
    // instead of ending up in the tree twice.
    child.remove();
    child.parentNode = this;
    const index = reference ? this.childNodes.indexOf(reference) : -1;
    if (index < 0) this.childNodes.push(child);
    else this.childNodes.splice(index, 0, child);
    return child;
  }

  get nextSibling() {
    if (!this.parentNode) return null;
    const index = this.parentNode.childNodes.indexOf(this);
    return this.parentNode.childNodes[index + 1] ?? null;
  }

  remove() {
    if (!this.parentNode) return;
    const index = this.parentNode.childNodes.indexOf(this);
    if (index >= 0) this.parentNode.childNodes.splice(index, 1);
    this.parentNode = null;
  }

  replaceChildren(...children) {
    this.childNodes = [];
    this.append(...children);
  }

  get textContent() {
    return this.childNodes.map((child) => child.textContent).join("");
  }

  set textContent(value) {
    this.childNodes = [];
    if (value !== "") this.append(new TextNode(String(value)));
  }
}

class TextNode extends Node_ {
  constructor(text) {
    super(3);
    this.data = text;
  }

  get textContent() {
    return this.data;
  }

  set textContent(value) {
    this.data = String(value);
  }
}

class Element_ extends Node_ {
  constructor(tag) {
    super(1);
    this.tagName = tag.toUpperCase();
    this.attributes = {};
    this.listeners = new Map();
    this.classList = new ClassList(this);
    // Form fields and editors read and write `value` and a caret.
    this.value = null;
    this.selectionStart = 0;
    this.selectionEnd = 0;
    this.setSelectionRange = (start, end) => {
      this.selectionStart = start;
      this.selectionEnd = end;
    };
  }
    setAttribute(name, value) {
    this.attributes[name] = String(value);
    // A canvas is looked up by its `id`, so one that acquires an id has to be
    // findable the way a browser would find it.
    if (name === "id" && globalThis.document?.register) {
      globalThis.document.register(String(value), this);
    }
  }

  getAttribute(name) {
    return this.attributes[name] ?? null;
  }

  removeAttribute(name) {
    delete this.attributes[name];
  }

  get className() {
    return this.attributes["class"] ?? "";
  }

  set className(value) {
    this.attributes["class"] = String(value);
  }

  get id() {
    return this.attributes["id"] ?? "";
  }

  set id(value) {
    this.attributes["id"] = String(value);
  }

  // A canvas reports its drawing surface as a number, and the compiler reads it
  // to clear the right area, so the two attributes a real element reflects are
  // reflected here too. Everything else stays an attribute.
  get width() {
    const value = Number(this.attributes["width"]);
    return Number.isFinite(value) ? value : 0;
  }

  set width(value) {
    this.attributes["width"] = String(value);
  }

  get height() {
    const value = Number(this.attributes["height"]);
    return Number.isFinite(value) ? value : 0;
  }

  set height(value) {
    this.attributes["height"] = String(value);
  }

  /** The highlighted HTML a code overlay wrote; a browser renders the markup. */
  get innerHTML() {
    return this._html ?? "";
  }

  set innerHTML(value) {
    this._html = String(value);
  }

  /** A recording 2D context, so canvas drawing is testable in the runner. */
  getContext(kind) {
    if (kind !== "2d") return null;
    if (this.__ctx2d) return this.__ctx2d;
    // The operations are methods rather than arrow functions so that `this` is
    // the context: a fill is recorded with the fill colour the drawing code
    // asked for, which is the only way a test can tell one fill from another.
    const ctx = {
      fillStyle: "black",
      fillRect(x, y, w, h) {
        (globalThis.__canvasOps ??= []).push({
          op: "fillRect",
          color: this.fillStyle,
          args: [x, y, w, h],
        });
      },
      clearRect(x, y, w, h) {
        (globalThis.__canvasOps ??= []).push({ op: "clearRect", args: [x, y, w, h] });
      },
      fillText(text, x, y) {
        (globalThis.__canvasOps ??= []).push({
          op: "fillText",
          text: String(text),
          args: [x, y],
        });
      },
    };
    this.__ctx2d = ctx;
    return ctx;
  }

  addEventListener(name, handler, options = false) {
    if (!this.listeners.has(name)) this.listeners.set(name, new Set());
    const capture = typeof options === "object" ? !!options.capture : !!options;
    this.listeners.get(name).add({ handler, capture });
  }

  removeEventListener(name, handler, options = false) {
    const capture = typeof options === "object" ? !!options.capture : !!options;
    const set = this.listeners.get(name);
    if (!set) return;
    for (const entry of [...set]) {
      if (entry.handler === handler && entry.capture === capture) set.delete(entry);
    }
  }

  dispatch(name, event = {}) {
    const handlers = this.listeners.get(name);
    if (!handlers) return 0;
    const entries = [...handlers];
    // Capturing listeners fire in the capture phase, bubbling ones after;
    // keeping the two phases separate means a capture-only registration
    // cannot silently behave like a bubble listener.
    for (const entry of entries.filter((e) => e.capture)) entry.handler(event);
    for (const entry of entries.filter((e) => !e.capture)) entry.handler(event);
    return entries.length;
  }

  /** How many handlers are still subscribed, so a test can prove they went. */
  listenerCount(name) {
    return this.listeners.get(name)?.size ?? 0;
  }

  walk() {
    const out = [this];
    for (const child of this.childNodes) {
      if (child.nodeType === 1) out.push(...child.walk());
    }
    return out;
  }

  find(predicate) {
    return this.walk().find(predicate) ?? null;
  }

  byText(text) {
    return this.find(
      (node) => node.nodeType === 1 && node.textContent === text,
    );
  }

  byTag(tag) {
    const upper = tag.toUpperCase();
    return this.walk().filter(
      (node) => node.nodeType === 1 && node.tagName === upper,
    );
  }
}

export function installDom() {
  const registry = new Map();
  globalThis.document = {
    createElement: (tag) => new Element_(tag),
    createTextNode: (text) => new TextNode(text),
    getElementById: (id) => registry.get(id) ?? null,
    register: (id, node) => registry.set(id, node),
    execCommand: (cmd) => {
      (globalThis.__execs ??= []).push(String(cmd));
      return true;
    },
    getSelection: () => globalThis.__selection ?? { rangeCount: 0, getRangeAt: () => ({ startOffset: 0, endOffset: 0 }) },
  };
  // Node has no caret, so the fixture drives `indent` through this cell.
  Object.defineProperty(globalThis.document, "activeElement", {
    get: () => globalThis.__active ?? null,
  });
  // The runtime reads browser globals, so the shim has to offer the same ones a
  // browser would.
  globalThis.innerWidth = 1024;
  globalThis.addEventListener = () => {};
  globalThis.localStorage = memoryStorage();
  globalThis.sessionStorage = memoryStorage();
  globalThis.__canvasOps = [];
  globalThis.__execs = [];
  globalThis.__selection = null;
  globalThis.__active = null;
  // An animation frame is a queue the harness flushes, so an `async fn` loop
  // can be driven frame by frame instead of on a real timer.
  globalThis.__rafQueue = [];
  globalThis.requestAnimationFrame = (callback) => {
    globalThis.__rafQueue.push(callback);
    return globalThis.__rafQueue.length;
  };
  // A real navigator (browser or Node) may be a getter-only property, so
  // augment it in place when it lacks a clipboard instead of replacing it.
  if (!globalThis.navigator || typeof globalThis.navigator.clipboard === "undefined") {
    const clipboard = {
      _text: "",
      async writeText(text) {
        this._text = String(text);
      },
      async readText() {
        return this._text;
      },
    };
    if (globalThis.navigator) {
      try {
        globalThis.navigator.clipboard = clipboard;
      } catch (err) {
        Object.defineProperty(globalThis, "navigator", {
          value: { clipboard },
          configurable: true,
          writable: true,
        });
      }
    } else {
      globalThis.navigator = { clipboard };
    }
  }
  globalThis.indexedDB = new BlankIndexedDB();
  globalThis.WebSocket = TestSocket;
  globalThis.showOpenFilePicker = showOpenFilePicker;
  return { Element: Element_, TextNode };
}

function memoryStorage() {
  const data = new Map();
  return {
    getItem: (key) => (data.has(key) ? data.get(key) : null),
    setItem: (key, value) => data.set(key, String(value)),
    removeItem: (key) => data.delete(key),
    clear: () => data.clear(),
    key: (index) => (index < data.size ? [...data.keys()][index] : null),
    get length() {
      return data.size;
    },
  };
}

/** A deterministic IndexedDB: `open` resolves immediately with a kv store. */
class BlankIndexedDB {
  constructor() {
    this._memory = new Map();
  }

  open() {
    const request = { error: null };
    request.result = {
      _memory: this._memory,
      createObjectStore: () => ({}),
      transaction() {
        const memory = this._memory;
        return {
          objectStore() {
            return {
              get: (key) => {
                const inner = { result: memory.get(key), error: null };
                queueMicrotask(() => inner.onsuccess?.({ target: inner }));
                return inner;
              },
              put: (value, key) => {
                memory.set(key, value);
                const inner = { result: true, error: null };
                queueMicrotask(() => inner.onsuccess?.({ target: inner }));
                return inner;
              },
              delete: (key) => {
                memory.delete(key);
                const inner = { result: true, error: null };
                queueMicrotask(() => inner.onsuccess?.({ target: inner }));
                return inner;
              },
            };
          },
        };
      },
    };
    queueMicrotask(() => request.onsuccess?.({ target: request }));
    return request;
  }
}

/** A socket for the test runner: opens, records sends, and echoes them back. */
class TestSocket {
  constructor(url) {
    this.url = url;
    this.readyState = 0;
    this.sent = [];
    (globalThis.__sockets ??= []).push(this);
    queueMicrotask(() => {
      this.readyState = 1;
      this.onopen?.({ type: "open" });
    });
  }

  send(data) {
    this.sent.push(String(data));
    // The showcase talks to an echo endpoint, so sending has to come back for
    // the send-and-receive path to mean anything under test.
    queueMicrotask(() => this.onmessage?.({ data: String(data) }));
  }

  close() {
    this.readyState = 3;
    this.onclose?.({ type: "close" });
  }
}

/** The file a picker hands back, shaped like the one a browser returns. */
class TestFile {
  constructor({ name = "", text = "", type = "" } = {}) {
    this.name = name;
    this.type = type || "text/plain";
    this._text = text;
    this.size = text.length;
  }

  text() {
    return Promise.resolve(this._text);
  }
}

/**
 * A picker a test can answer: set `globalThis.__pick` to the file to return, or
 * to `null` to stand in for the user dismissing the dialog.
 */
function showOpenFilePicker() {
  const pick = globalThis.__pick;
  if (pick === undefined) return Promise.reject(new Error("no file to pick"));
  if (pick === null) return Promise.resolve([]);
  return Promise.resolve([{ getFile: () => Promise.resolve(new TestFile(pick)) }]);
}

export { Element_ as Element, TextNode };
"#;

pub fn render() -> String {
    SOURCE.to_string()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_shim_exports_what_a_runner_needs() {
        for name in ["installDom", "export { Element_ as Element"] {
            assert!(SOURCE.contains(name), "missing {name}");
        }
    }

    #[test]
    fn the_shim_offers_the_globals_the_runtime_reads() {
        for name in ["createElement", "createTextNode", "getElementById"] {
            assert!(SOURCE.contains(name), "missing {name}");
        }
        assert!(SOURCE.contains("globalThis.innerWidth"));
        assert!(SOURCE.contains("globalThis.sessionStorage"));
        assert!(SOURCE.contains("globalThis.navigator"));
        assert!(SOURCE.contains("globalThis.indexedDB"));
        assert!(SOURCE.contains("globalThis.WebSocket"));
    }

    #[test]
    fn the_shim_supports_the_advanced_ui_surface() {
        for name in [
            "getContext",
            "globalThis.__canvasOps",
            "globalThis.__execs",
            "globalThis.requestAnimationFrame",
            "execCommand",
            "getSelection",
            "activeElement",
        ] {
            assert!(SOURCE.contains(name), "missing {name}");
        }
    }

    #[test]
    fn the_shim_covers_every_node_operation_the_runtime_uses() {
        for name in [
            "insertBefore",
            "replaceChildren",
            "setAttribute",
            "removeAttribute",
            "addEventListener",
            "removeEventListener",
            "nextSibling",
            "textContent",
        ] {
            assert!(SOURCE.contains(name), "missing {name}");
        }
    }
}
